/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint64Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint64StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface CoffheeSwapInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositTokenA"
      | "depositTokenB"
      | "owner"
      | "rateAToBDenominator"
      | "rateAToBNumerator"
      | "rateBToADenominator"
      | "rateBToANumerator"
      | "renounceOwnership"
      | "setRates"
      | "swapAForB"
      | "swapBForA"
      | "tokenA"
      | "tokenB"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RatesUpdated"
      | "SwapAForB"
      | "SwapBForA"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "depositTokenA",
    values: [InEuint64Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "depositTokenB",
    values: [InEuint64Struct]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rateAToBDenominator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rateAToBNumerator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rateBToADenominator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rateBToANumerator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRates",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAForB",
    values: [InEuint64Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "swapBForA",
    values: [InEuint64Struct]
  ): string;
  encodeFunctionData(functionFragment: "tokenA", values?: undefined): string;
  encodeFunctionData(functionFragment: "tokenB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositTokenA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositTokenB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rateAToBDenominator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateAToBNumerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateBToADenominator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateBToANumerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRates", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapAForB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapBForA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatesUpdatedEvent {
  export type InputTuple = [
    aToBNumerator: BigNumberish,
    aToBDenominator: BigNumberish,
    bToANumerator: BigNumberish,
    bToADenominator: BigNumberish
  ];
  export type OutputTuple = [
    aToBNumerator: bigint,
    aToBDenominator: bigint,
    bToANumerator: bigint,
    bToADenominator: bigint
  ];
  export interface OutputObject {
    aToBNumerator: bigint;
    aToBDenominator: bigint;
    bToANumerator: bigint;
    bToADenominator: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapAForBEvent {
  export type InputTuple = [sender: AddressLike];
  export type OutputTuple = [sender: string];
  export interface OutputObject {
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapBForAEvent {
  export type InputTuple = [sender: AddressLike];
  export type OutputTuple = [sender: string];
  export interface OutputObject {
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoffheeSwap extends BaseContract {
  connect(runner?: ContractRunner | null): CoffheeSwap;
  waitForDeployment(): Promise<this>;

  interface: CoffheeSwapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositTokenA: TypedContractMethod<
    [encryptedAmount: InEuint64Struct],
    [void],
    "nonpayable"
  >;

  depositTokenB: TypedContractMethod<
    [encryptedAmount: InEuint64Struct],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  rateAToBDenominator: TypedContractMethod<[], [bigint], "view">;

  rateAToBNumerator: TypedContractMethod<[], [bigint], "view">;

  rateBToADenominator: TypedContractMethod<[], [bigint], "view">;

  rateBToANumerator: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setRates: TypedContractMethod<
    [
      _rateAToBNumerator: BigNumberish,
      _rateAToBDenominator: BigNumberish,
      _rateBToANumerator: BigNumberish,
      _rateBToADenominator: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  swapAForB: TypedContractMethod<
    [encryptedAmountIn: InEuint64Struct],
    [void],
    "nonpayable"
  >;

  swapBForA: TypedContractMethod<
    [encryptedAmountIn: InEuint64Struct],
    [void],
    "nonpayable"
  >;

  tokenA: TypedContractMethod<[], [string], "view">;

  tokenB: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositTokenA"
  ): TypedContractMethod<
    [encryptedAmount: InEuint64Struct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositTokenB"
  ): TypedContractMethod<
    [encryptedAmount: InEuint64Struct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rateAToBDenominator"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rateAToBNumerator"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rateBToADenominator"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rateBToANumerator"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRates"
  ): TypedContractMethod<
    [
      _rateAToBNumerator: BigNumberish,
      _rateAToBDenominator: BigNumberish,
      _rateBToANumerator: BigNumberish,
      _rateBToADenominator: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapAForB"
  ): TypedContractMethod<
    [encryptedAmountIn: InEuint64Struct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapBForA"
  ): TypedContractMethod<
    [encryptedAmountIn: InEuint64Struct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenA"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenB"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RatesUpdated"
  ): TypedContractEvent<
    RatesUpdatedEvent.InputTuple,
    RatesUpdatedEvent.OutputTuple,
    RatesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SwapAForB"
  ): TypedContractEvent<
    SwapAForBEvent.InputTuple,
    SwapAForBEvent.OutputTuple,
    SwapAForBEvent.OutputObject
  >;
  getEvent(
    key: "SwapBForA"
  ): TypedContractEvent<
    SwapBForAEvent.InputTuple,
    SwapBForAEvent.OutputTuple,
    SwapBForAEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RatesUpdated(uint64,uint64,uint64,uint64)": TypedContractEvent<
      RatesUpdatedEvent.InputTuple,
      RatesUpdatedEvent.OutputTuple,
      RatesUpdatedEvent.OutputObject
    >;
    RatesUpdated: TypedContractEvent<
      RatesUpdatedEvent.InputTuple,
      RatesUpdatedEvent.OutputTuple,
      RatesUpdatedEvent.OutputObject
    >;

    "SwapAForB(address)": TypedContractEvent<
      SwapAForBEvent.InputTuple,
      SwapAForBEvent.OutputTuple,
      SwapAForBEvent.OutputObject
    >;
    SwapAForB: TypedContractEvent<
      SwapAForBEvent.InputTuple,
      SwapAForBEvent.OutputTuple,
      SwapAForBEvent.OutputObject
    >;

    "SwapBForA(address)": TypedContractEvent<
      SwapBForAEvent.InputTuple,
      SwapBForAEvent.OutputTuple,
      SwapBForAEvent.OutputObject
    >;
    SwapBForA: TypedContractEvent<
      SwapBForAEvent.InputTuple,
      SwapBForAEvent.OutputTuple,
      SwapBForAEvent.OutputObject
    >;
  };
}
